# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fa9b571bbd438a4affd67223fa31b529df123e1428661dbe8e904f1bfe611d8bef76550143206b55c2932c028bfd1de8c071023acff0804e1ad91e25e87ed80

test:
  secret_key_base: a073aa1ae79aec0a5a0761c9710db94e127bb749ae7dc1bd749625935e31d16b608bc77dd7dbbcdd800d79b4b0967b4b2e04360567df1842b976cf992d743cd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
